//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ifun.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberOfSystem
    {
        public int ID { get; set; }
        public Nullable<int> SystemOrderId { get; set; }
        public Nullable<int> Game_SystemID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
    
        public virtual Gamesystem Gamesystem { get; set; }
    }
}
