USE [master]
GO

/****** Object:  Database [iFun]    Script Date: 06/01/2017 23:30:55 ******/
CREATE DATABASE [iFun] ON  PRIMARY 
( NAME = N'iFun', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\iFun.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'iFun_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\iFun_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [iFun] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [iFun].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [iFun] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [iFun] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [iFun] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [iFun] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [iFun] SET ARITHABORT OFF 
GO

ALTER DATABASE [iFun] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [iFun] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [iFun] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [iFun] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [iFun] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [iFun] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [iFun] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [iFun] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [iFun] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [iFun] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [iFun] SET  DISABLE_BROKER 
GO

ALTER DATABASE [iFun] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [iFun] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [iFun] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [iFun] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [iFun] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [iFun] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [iFun] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [iFun] SET  READ_WRITE 
GO

ALTER DATABASE [iFun] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [iFun] SET  MULTI_USER 
GO

ALTER DATABASE [iFun] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [iFun] SET DB_CHAINING OFF 
GO


